services:
  dumbproxy:
    image: ghcr.io/senseunit/dumbproxy@sha256:a7db13dae10d564722872c08cc37f6417be551dcbe6aa8faa4e81cb34d79e6f8
    container_name: dumbproxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: -bind-address :8080 -auth 'static://?username=admin&password=admin'
    user: "1000:1000"
    cpus: "0.5"
    mem_limit: 128M
